/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yazıeditor;
import java.util.Stack;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JTextPane;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;
/**
 *
 * @author Lenovo
 */
public class Arayuz extends javax.swing.JFrame {

    /**
     * Creates new form Arayuz
     */
    public Arayuz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        geriAl = new javax.swing.JMenu();
        ileriAl = new javax.swing.JMenu();
        italic = new javax.swing.JMenu();
        bold = new javax.swing.JMenu();
        hbhi = new javax.swing.JMenu();
        normal = new javax.swing.JMenu();
        timesNewRoman = new javax.swing.JMenu();
        impact = new javax.swing.JMenu();
        comicSans = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jTextPane.getDocument().addUndoableEditListener(new UndoableEditListener() {
            public void undoableEditHappened(UndoableEditEvent e) {
                um.addEdit(e.getEdit());
            }
        });
        jTextPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPaneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPaneKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPane);

        geriAl.setText("Undo");
        geriAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriAlMouseClicked(evt);
            }
        });
        jMenuBar1.add(geriAl);

        ileriAl.setText("Rodo");
        ileriAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ileriAlMouseClicked(evt);
            }
        });
        ileriAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ileriAlActionPerformed(evt);
            }
        });
        jMenuBar1.add(ileriAl);

        italic.setText("İtalic Yap");
        italic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                italicMouseClicked(evt);
            }
        });
        jMenuBar1.add(italic);

        bold.setText("Bold Yap");
        bold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boldMouseClicked(evt);
            }
        });
        jMenuBar1.add(bold);

        hbhi.setText("Hem Bold Hem İtalic");
        hbhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hbhiMouseClicked(evt);
            }
        });
        jMenuBar1.add(hbhi);

        normal.setText("Normale Dön");
        normal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normalMouseClicked(evt);
            }
        });
        jMenuBar1.add(normal);

        timesNewRoman.setText("Times New Roman");
        timesNewRoman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timesNewRomanMouseClicked(evt);
            }
        });
        jMenuBar1.add(timesNewRoman);

        impact.setText("İmpact");
        impact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                impactMouseClicked(evt);
            }
        });
        jMenuBar1.add(impact);

        comicSans.setText("Comic Sans MS");
        comicSans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comicSansMouseClicked(evt);
            }
        });
        jMenuBar1.add(comicSans);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int i = 0;
    int k = 0;
    int sonindex =0;
    Stack undo = new Stack();
    Stack redo = new Stack();
    public Dugum ilk = null;
    UndoManager um = new UndoManager();
    
   public void Undo(){
   
       um.undo();
   
   }
   
   public void Redo(){
   
       um.redo();
   
   }
    
    private void ileriAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ileriAlActionPerformed
        
    }//GEN-LAST:event_ileriAlActionPerformed

    private void geriAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriAlMouseClicked
        this.Undo();
    }//GEN-LAST:event_geriAlMouseClicked

    private void jTextPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaneKeyPressed
//        if(evt.getKeyChar() == ' '){
//
//            if(evt.getKeyChar() == ' ')
//        {
//            String yazi = jTextPane.getText();
//        
//            String kelime = yazi.substring(sonindex, yazi.length()-1);
//            
//            undo.push(new Dugum(i, kelime));
//            
//            sonindex = i+1;
//        }
//        
//        i++;
//        }
        
//        switch(evt.getKeyCode()){
//            case 26 -> this.Undo();
//            case 25 -> this.Redo();
//        }
//        if(evt.getKeyCode() == 26){
//            this.Undo();
//        }
//        
//        if(evt.isControlDown() == true){
//            k = 1;
//        }
//        if(evt.getKeyChar() == 'z' && k == 1){
//            this.Undo();
//        }
//        if(k == 1){
//            this.Undo();
//            k = 0;
//        }

        if(evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_Z){
            this.Undo();
        }
        if(evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_Y){
            this.Redo();
        }
//        while(evt.isControlDown() == true){
//            if(evt.getKeyChar() == 'z'){
//            this.Undo();
//            this.Undo();
//        }
//        }
//        
    }//GEN-LAST:event_jTextPaneKeyPressed

    private void italicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italicMouseClicked
        Font font = new Font("Baskerville", Font.ITALIC, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_italicMouseClicked

    private void boldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldMouseClicked
        Font font = new Font("Baskerville", Font.BOLD, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_boldMouseClicked

    private void normalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalMouseClicked
        Font font = new Font("Baskerville", Font.PLAIN, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_normalMouseClicked

    private void timesNewRomanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timesNewRomanMouseClicked
        Font font = new Font("Times New Roman", Font.PLAIN, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_timesNewRomanMouseClicked

    private void impactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_impactMouseClicked
        Font font = new Font("Impact", Font.PLAIN, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_impactMouseClicked

    private void comicSansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comicSansMouseClicked
        Font font = new Font("Comic Sans MS", Font.PLAIN, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_comicSansMouseClicked

    private void hbhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hbhiMouseClicked
        Font font = new Font("Baskerville", Font.BOLD | Font.ITALIC, 12);
        jTextPane.setFont(font);
    }//GEN-LAST:event_hbhiMouseClicked

    private void ileriAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ileriAlMouseClicked
        this.Redo();
    }//GEN-LAST:event_ileriAlMouseClicked

    private void jTextPaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaneKeyTyped
//        while(evt.isControlDown() == true){
//            if(evt.getKeyChar() == 'z'){
//                this.Undo();
//                this.Undo();
//            }
//        }
//
//        if(evt.getKeyCode() == 26){
//            this.Undo();
//        }
    }//GEN-LAST:event_jTextPaneKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
//        if(evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_Z){
//            this.Undo();
//        }
//        if(evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_Y){
//            this.Redo();
//        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bold;
    private javax.swing.JMenu comicSans;
    private javax.swing.JMenu geriAl;
    private javax.swing.JMenu hbhi;
    private javax.swing.JMenu ileriAl;
    private javax.swing.JMenu impact;
    private javax.swing.JMenu italic;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane;
    private javax.swing.JMenu normal;
    private javax.swing.JMenu timesNewRoman;
    // End of variables declaration//GEN-END:variables
}
